### ISSUE TITLE
Starting slide index prop

### ISSUE THREAD

**Issue by mikimoresi** [BKWLD/vue-ssr-carousel#92]
Dear Sirs,
very nice component.
Would be great to have the starting index as a prop so that is possible to set the slider to start from a specific slide and not from the default 0.

Actually I'm using the goto() method after component load but is not that nice to see.

Thank you

**Comment by weotch** [comment]
I like that idea. Supporting `.sync` would be cool too, so one could use this to trigger updates to the current slide.

**Comment by mikimoresi** [comment]
I have added the possibility to use the `goto()` function giving an extra boolean parameter that run the function without using animation so that it can be used instead of a starting index prop.

If for example you need your slider to appear positioned on slide number 5 just call `goto(5, true)` on `mounted`

`this.$refs['ssrcarousel'].goto(5,true);`


I have also created a pull request and I hope they will accept this feature in the official project.
https://github.com/BKWLD/vue-ssr-carousel/pull/96

**Comment by weotch** [comment]
I took an alternate approach with #100 and added `v-model` support.  Check out the new demo at the top of https://vue-ssr-carousel.netlify.app/events.  I don't love that flicker that you see between slide 1 and 2 but it's unavoidable since I depend on measuring the size of elements client side when setting the offset of the slide track.
